//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public int StudentID { get; set; }
        public int FacultyID { get; set; }
        public DateTime AppointmentDateTime { get; set; }
        public DateTime AppointmentDatetime { get; internal set; }
        public string AppointmentDescription { get; set; }
        public string Status { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual Student Student { get; set; }
    }
}
